apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 32080   # Match the container port mapped by KIND for HTTP
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 32443   # Match the container port mapped by KIND for HTTPS
      nodePort: 30443
